### ISSUE TITLE
Nominatim fails with addresses that contain Suite numbers

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#81]
When adding a company that has a suite number mrcli will crash because of nominatim.

Example:

ProductPlan
Headquarters Location
836 Anacapa Street Suite 944
Santa Barbara, California, 93101,
United States
805-618-2975

```
async getLatLong(address) {
        const response = await axios.get(`https://nominatim.openstreetmap.org/search?q=${address}&format=json`)
        if (response.data && response.data[0]) {
            return [true, {status_code: 200, status_msg: `found coordinates for ${address}`}, [parseFloat(response.data[0].lat), parseFloat(response.data[0].lon)]]
        } else {
            return [false, {status_code: 404, status_msg: `could not find coordinates for ${address}`}, null]
        }
    }

```

**Comment by miha42-github** [comment]
Also fails intermittently with

```
file:///Users/mihay42/dev/mediumroast_js/src/cli/companyWizard.js:561
            const [status, msg, [lat, long]] = await this.getLatLong(fullAddress)
                                ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at AddCompany.doAutomatic (file:///Users/mihay42/dev/mediumroast_js/src/cli/companyWizard.js:561:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCompany.wizard (file:///Users/mihay42/dev/mediumroast_js/src/cli/companyWizard.js:762:21)
    at async file:///Users/mihay42/dev/mediumroast_js/cli/mrcli-company.js:271:19

Node.js v20.9.0
```

This could be a signal that the serrvice is busy and should be changed.  We will look to run an experiement where alternative service is used.

**Comment by miha42-github** [comment]
The method for accessing the geocoding was improved with a Node.js module.  Additionally, producing the address string was made more robust in that should incomplete information be present then some sense of a geospatial outcome is still possible.  Will test with a few companies to judge the robustness of the process.

**Comment by miha42-github** [comment]
Confirmed resolved
