### ISSUE TITLE
mrcli my_user errors out

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#83]
mrcli u --my_user                                                                                                                                           1 ✘  john@medici  03:48:50
/usr/local/lib/node_modules/mediumroast_js/node_modules/cli-table/lib/index.js:188
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                          ^

TypeError: Cannot read properties of null (reading 'toString')
    at /usr/local/lib/node_modules/mediumroast_js/node_modules/cli-table/lib/index.js:188:27
    at Array.forEach (<anonymous>)
    at generateRow (/usr/local/lib/node_modules/mediumroast_js/node_modules/cli-table/lib/index.js:187:11)
    at /usr/local/lib/node_modules/mediumroast_js/node_modules/cli-table/lib/index.js:281:16
    at Table.forEach (<anonymous>)
    at Table.toString (/usr/local/lib/node_modules/mediumroast_js/node_modules/cli-table/lib/index.js:264:10)
    at CLIOutput.outputTable (file:///usr/local/lib/node_modules/mediumroast_js/src/cli/output.js:148:27)
    at CLIOutput.outputCLI (file:///usr/local/lib/node_modules/mediumroast_js/src/cli/output.js:40:18)
    at file:///usr/local/lib/node_modules/mediumroast_js/cli/mrcli-user.js:81:17

**Comment by miha42-github** [comment]
@jgoodie please verify that this is no longer a problem

**Comment by miha42-github** [comment]
Stale and likely fixed closing
